"""restructure_tracked_users_for_removal_workflow

Revision ID: c67dd4c23e18
Revises: cbf4ef4ca236
Create Date: 2025-07-22 20:53:40.528132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67dd4c23e18'
down_revision: Union[str, None] = 'cbf4ef4ca236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('tracked_users', sa.Column('guild_id', sa.String(), nullable=False))
    op.add_column('tracked_users', sa.Column('removal_status', sa.Enum('ACTIVE', 'PENDING_REMOVAL', 'FIRST_WARNING_SENT', 'FINAL_NOTICE_SENT', 'REMOVED', name='removalstatus'), nullable=False))
    op.add_column('tracked_users', sa.Column('removal_date', sa.DateTime(), nullable=True))
    op.add_column('tracked_users', sa.Column('first_warning_sent_at', sa.DateTime(), nullable=True))
    op.add_column('tracked_users', sa.Column('final_notice_sent_at', sa.DateTime(), nullable=True))
    op.add_column('tracked_users', sa.Column('removed_at', sa.DateTime(), nullable=True))
    op.add_column('tracked_users', sa.Column('first_warning_message_id', sa.String(), nullable=True))
    op.add_column('tracked_users', sa.Column('final_notice_message_id', sa.String(), nullable=True))
    op.add_column('tracked_users', sa.Column('removal_message_id', sa.String(), nullable=True))
    op.drop_column('tracked_users', 'marked_for_removal')
    op.drop_column('tracked_users', 'kicked_at')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_users', sa.Column('kicked_at', sa.DATETIME(), nullable=True))
    op.add_column('tracked_users', sa.Column('marked_for_removal', sa.BOOLEAN(), nullable=False))
    op.drop_column('tracked_users', 'removal_message_id')
    op.drop_column('tracked_users', 'final_notice_message_id')
    op.drop_column('tracked_users', 'first_warning_message_id')
    op.drop_column('tracked_users', 'removed_at')
    op.drop_column('tracked_users', 'final_notice_sent_at')
    op.drop_column('tracked_users', 'first_warning_sent_at')
    op.drop_column('tracked_users', 'removal_date')
    op.drop_column('tracked_users', 'removal_status')
    op.drop_column('tracked_users', 'guild_id')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ### 