"""Add guild object

Revision ID: cbf4ef4ca236
Revises: 38c6aa65cf32
Create Date: 2025-07-22 20:23:16.322975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf4ef4ca236'
down_revision: Union[str, None] = '38c6aa65cf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guilds')
    # ### end Alembic commands ### 