name: PatsBot CI

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_PATS: ghcr.io/snowsune/pats-bot

jobs:
  formatblack:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

  build-and-publish-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: [formatblack]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sanitize branch name for tag
        id: vars
        run: |
          BRANCH_TAG=$(echo "${GITHUB_REF_NAME}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "BRANCH_TAG=$BRANCH_TAG" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          load: true
          tags: |
            ${{ env.IMAGE_PATS }}:latest
            ${{ env.IMAGE_PATS }}:${{ env.BRANCH_TAG }}

      - name: Get Docker image size
        id: image_size
        run: |
          SIZE=$(docker images ${{ env.IMAGE_PATS }}:latest --format "{{.Size}}")
          echo "IMAGE_SIZE=$SIZE" >> $GITHUB_ENV

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: ncatelli/action-discord@115-add-wait-parameter-prefix
        with:
          args: "Built and published a new PatsBot docker image to `${{ env.IMAGE_PATS }}:latest` and `${{ env.IMAGE_PATS }}:${{ env.BRANCH_TAG }}`! Image size: `${{ env.IMAGE_SIZE }}`" 